# -*- coding: utf-8 -*-
"""物品 id（minecraft: 后缀短名）-> 中文名（中文 Wiki 名）。

六张战利品表全集 + 后续补全的结构专属物品，供 StructurePreviewer
战利品展示与「查找物品」定位窗口的物品下拉共用（单一数据源）。
"""

ITEM_CN = {
    "ancient_debris": "远古残骸", "apple": "苹果", "arrow": "箭",
    "bamboo": "竹子", "beetroot_seeds": "甜菜种子", "bone_block": "骨块", "book": "书",
    "buried_treasure_map": "埋藏的宝藏地图", "carrot": "胡萝卜",
    "chain": "锁链", "clock": "时钟", "coal": "煤炭",
    "coast_armor_trim_smithing_template": "海岸盔甲纹样锻造模板",
    "compass": "指南针", "cooked_porkchop": "熟猪排",
    "copper_horse_armor": "铜马铠",
    "copper_nautilus_armor": "铜鹦鹉螺铠",
    "crying_obsidian": "哭泣的黑曜石",
    "crossbow": "弩", "dark_oak_log": "深色橡木原木", "diamond": "钻石",
    "diamond_boots": "钻石靴子", "diamond_chestplate": "钻石胸甲",
    "diamond_helmet": "钻石头盔",
    "diamond_horse_armor": "钻石马铠", "diamond_leggings": "钻石护腿",
    "diamond_nautilus_armor": "钻石鹦鹉螺铠",
    "diamond_pickaxe": "钻石镐", "diamond_spear": "钻石矛",
    "diamond_shovel": "钻石锹", "diamond_sword": "钻石剑", "emerald": "绿宝石",
    "experience_bottle": "附魔之瓶", "feather": "羽毛",
    "flint_and_steel": "打火石", "gilded_blackstone": "镀金黑石",
    "gold_block": "金块", "gold_ingot": "金锭", "gold_nugget": "金粒",
    "golden_apple": "金苹果", "golden_axe": "金斧",
    "golden_boots": "金靴子", "golden_carrot": "金胡萝卜",
    "golden_chestplate": "金胸甲", "golden_helmet": "金头盔",
    "golden_horse_armor": "金马铠", "golden_leggings": "金护腿",
    "golden_nautilus_armor": "金鹦鹉螺铠", "golden_sword": "金剑",
    "goat_horn": "山羊角", "gunpowder": "火药",
    "iron_block": "铁块", "iron_boots": "铁靴子",
    "iron_chestplate": "铁胸甲", "iron_helmet": "铁头盔",
    "iron_horse_armor": "铁马铠", "iron_leggings": "铁护腿",
    "iron_nautilus_armor": "铁鹦鹉螺铠", "iron_ingot": "铁锭", "iron_nugget": "铁粒",
    "iron_pickaxe": "铁镐", "iron_shovel": "铁锹", "iron_sword": "铁剑",
    "lapis_lazuli": "青金石", "leather": "皮革",
    "leather_boots": "皮革靴子", "leather_chestplate": "皮革胸甲",
    "leather_helmet": "皮革帽子", "leather_leggings": "皮革裤子",
    "lodestone": "磁石", "magma_cream": "岩浆膏", "map": "地图",
    "moss_block": "苔藓块", "music_disc_pigstep": "音乐唱片（Pigstep）",
    "nether_wart": "下界疣", "netherite_scrap": "下界合金碎片",
    "netherite_upgrade_smithing_template": "下界合金升级锻造模板",
    "obsidian": "黑曜石", "paper": "纸",
    "piglin_banner_pattern": "猪灵旗帜图案",
    "poisonous_potato": "毒马铃薯", "potato": "马铃薯",
    "pumpkin": "南瓜", "rib_armor_trim_smithing_template": "肋骨盔甲纹样锻造模板",
    "rotten_flesh": "腐肉", "saddle": "鞍",
    "spire_armor_trim_smithing_template": "尖塔盔甲纹样锻造模板",
    "spectral_arrow": "光灵箭", "stone_axe": "石斧", "string": "线",
    "suspicious_stew": "迷之炖菜", "tnt": "TNT", "wheat": "小麦",
    # -- 试炼密室 9 表物品补全（中文 Wiki 名）--
    "acacia_planks": "金合欢木板", "amethyst_shard": "紫水晶碎片",
    "baked_potato": "烤马铃薯", "bamboo_hanging_sign": "竹制悬挂式告示牌",
    "bamboo_planks": "竹木板", "bolt_armor_trim_smithing_template":
        "旋风盔甲纹样锻造模板",
    "bone_meal": "骨粉", "bow": "弓", "bucket": "铁桶", "cake": "蛋糕",
    "diamond_axe": "钻石斧", "diamond_block": "钻石块",
    "emerald_block": "绿宝石块", "ender_pearl": "末影珍珠",
    "glow_berries": "发光浆果", "golden_pickaxe": "金镐",
    "guster_banner_pattern": "旋风旗帜图案", "honey_bottle": "蜂蜜瓶",
    "honeycomb": "蜜脾", "iron_axe": "铁斧", "milk_bucket": "牛奶桶",
    "music_disc_precipice": "音乐唱片（Precipice）",
    "ominous_bottle": "不祥之瓶", "potion": "药水", "scaffolding": "脚手架",
    "shield": "盾牌", "stick": "木棍", "stone_pickaxe": "石镐",
    "tipped_arrow": "药水箭", "torch": "火把", "trial_key": "试炼钥匙",
    "trident": "三叉戟", "tuff": "凝灰岩", "wind_charge": "风弹",
    "wooden_axe": "木斧",
    # -- 要塞 3 表物品补全（中文 Wiki 名）--
    "bread": "面包", "redstone": "红石粉",
"music_disc_otherside": "音乐唱片（Otherside）",
    "eye_armor_trim_smithing_template": "眼畦盔甲纹样锻造模板",
    # -- 林地府邸表物品补全（中文 Wiki 名）--
    "lead": "拴绳", "enchanted_golden_apple": "附魔金苹果",
    "music_disc_13": "音乐唱片（13）", "music_disc_cat": "音乐唱片（cat）",
    "name_tag": "命名牌", "chainmail_chestplate": "锁链胸甲",
    "diamond_hoe": "钻石钻", "melon_seeds": "西瓜种子",
    "pumpkin_seeds": "南瓜种子", "resin_clump": "树脂团",
    "bone": "骨头",
    "vex_armor_trim_smithing_template": "恼鬼盔甲纹样锻造模板",
    # -- 远古城市两表物品补全（中文 Wiki 名）--
    "echo_shard": "回响碎片", "disc_fragment_5": "唱片残片（5）",
    "sculk": "幽匿块", "sculk_sensor": "幽匿感测体",
    "sculk_catalyst": "幽匿催发体", "soul_torch": "灵魂火把",
    "candle": "蜡烛", "packed_ice": "浮冰", "snowball": "雪球",
    "ward_armor_trim_smithing_template": "守卫盔甲纹样锻造模板",
    "silence_armor_trim_smithing_template": "沉静盔甲纹样锻造模板",
    # -- 海底废墟/掠夺者前哨站/堡垒遗迹漏网物品补全（中文 Wiki 名）--
    "fishing_rod": "钓鱼竿", "stone_spear": "石矛",
    "sentry_armor_trim_smithing_template": "哨兵盔甲纹样锻造模板",
    "snout_armor_trim_smithing_template": "猪鼻盔甲纹样锻造模板",
    "tripwire_hook": "绊线钩",
    # -- 村庄表物品补全（中文 Wiki 名）--
    "bundle": "收纳袋", "dandelion": "蒲公英", "oak_sapling": "橡树苗",
    # -- 沙漠神殿/丛林神庙表物品补全（中文 Wiki 名）--
    "sand": "沙子", "spider_eye": "蜘蛛眼",
    "dune_armor_trim_smithing_template": "沙丘盔甲纹样锻造模板",
    "wild_armor_trim_smithing_template": "荒野盔甲纹样锻造模板",
    # -- 废弃传送门/埋藏的宝藏表物品补全（中文 Wiki 名）--
    "bell": "钟", "fire_charge": "火焰弹", "flint": "燧石",
    "glistering_melon_slice": "闪烁的西瓜片",
    "golden_hoe": "金锄", "golden_shovel": "金锹",
    "light_weighted_pressure_plate": "轻质测重压力板",
    "heart_of_the_sea": "海洋之心", "prismarine_crystals": "海晶结晶",
    "cooked_cod": "熟鳕鱼", "cooked_salmon": "熟鲑鱼",
    "iron_spear": "铁矛",
}